### PR TITLE
Code fixes

### LINKED ISSUE #2: unreachable code issue
It seems as if there is an issue building https://github.com/Luukdegram/lemon/blob/master/src/object.zig#L137-L182

trying to do so gives 
```
C:\Users\infrandomness\Documents\Dev\Zig\lemon\src\object.zig:141:9: error: unreachable code
        const kind = kindToString(self.kind);
        ^
C:\Users\infrandomness\Documents\Dev\Zig\lemon\src\object.zig:140:9: note: control flow is diverted here
        @compileError("TODO implement when zlib compression is supported");
        ^
```

This seems related to https://github.com/ziglang/zig/issues/8631

However, it also looks [std.compress.zlig](https://github.com/ziglang/zig/blob/master/lib/std/compress/zlib.zig) doesn't contain any function to compress data.

What would be the right way to fix this problem?

### PR DESCRIPTION
**Pull request by ghost**
This pull request proposes code-fixes to make the codebase compile back again on zig `0.9.0-dev.856+dd7530256`

Fixes https://github.com/Luukdegram/lemon/issues/2

### CODE REVIEW

File: cli/cmds.zig [hunk 1]
```diff
@@ -157,7 +161,7 @@ fn handleLog(gpa: *Allocator, args: [][]const u8, writer: anytype) !void {
 
 /// Shows a list of all tags or creates a new one if a name argument is given
 fn handleTag(gpa: *Allocator, args: [][]const u8, writer: anytype) !void {
-    const name = if (args.len > 1) args[1] else null;
+    _ = if (args.len > 1) args[1] else null;
```
Comment (Luukdegram) [inline cli/cmds.zig]: This line can be fully removed or have a `@panic("todo")` as it hasn't been implemented yet to create a tag.

**Review by Luukdegram — CHANGES_REQUESTED** [review]

File: cli/cmds.zig (hunk 1 above)
Comment (ghost) [reply cli/cmds.zig]: `@panic()` would lead to the same issue as in https://github.com/Luukdegram/lemon/issues/2, would it be fair to replace it with this instead : 

```zig
    // TODO: Implement tag creation
    _ = args;
```

**Comment by ghost** [comment]
Troubles building the code have been experienced on a multiline string.

I have created an issue upstream to track it : https://github.com/ziglang/zig/issues/9625

**Comment by Luukdegram** [comment]
> Troubles building the code have been experienced on a multiline string.
> 
> 
> 
> I have created an issue upstream to track it : https://github.com/ziglang/zig/issues/9625

I guess you're on Windows. Does running 'zig fmt' on the file fix it? I think this is due to stage1's parser finding a \r\n line ending.

**Comment by ghost** [comment]
> > Troubles building the code have been experienced on a multiline string.
> > I have created an issue upstream to track it : [ziglang/zig#9625](https://github.com/ziglang/zig/issues/9625)
> 
> I guess you're on Windows. Does running 'zig fmt' on the file fix it? I think this is due to stage1's parser finding a \r\n line ending.

good catch, I totally forgot that

File: build.zig [hunk 2]
```diff
@@ -1,4 +1,6 @@
 const std = @import("std");
+const deps = @import("./deps.zig");
```
Comment (Luukdegram) [inline build.zig]: Can we not use `zigmod` please? I'd rather not install some hobby package manager to make this work. We could just have a `libs` folder that contains the zlib library, and link with it in `build.zig`.

**Review by Luukdegram — CHANGES_REQUESTED** [review]

File: build.zig (hunk 2 above)
Comment (ghost) [reply build.zig]: Sure, I was thinking of having this to integrate better with the other tooling down the line.

How about using git submodules instead?

Comment (Luukdegram) [reply build.zig]: Yeah git submodules is good too!

File: cli/cmds.zig (hunk 1 above)
Comment (ghost) [reply cli/cmds.zig]: Fixed in https://github.com/Luukdegram/lemon/pull/1/commits/d1ffd057edf7bda2a5a68b0934c08f4e4fa42de7

File: build.zig (hunk 2 above)
Comment (ghost) [reply build.zig]: Fixed in https://github.com/Luukdegram/lemon/pull/1/commits/9ca6cbdbe2267befa21570cdb7838612bf3671a0

File: deps.zig [hunk 3]
```diff
@@ -0,0 +1,78 @@
+const std = @import("std");
```
Comment (Luukdegram) [inline deps.zig]: This file can be deleted as we use submodules

File: cli/cmds.zig [hunk 4]
```diff
@@ -152,12 +156,13 @@ fn handleLog(gpa: *Allocator, args: [][]const u8, writer: anytype) !void {
...
     defer ref.deinit(gpa);
 
-    try writer.print("{} {}", .{ ref.name, ref.hash });
+    try writer.print("{s} {s}", .{ ref.name, ref.hash });
 }
 
 /// Shows a list of all tags or creates a new one if a name argument is given
 fn handleTag(gpa: *Allocator, args: [][]const u8, writer: anytype) !void {
-    const name = if (args.len > 1) args[1] else null;
+    std.debug.panic("//TODO: Implement tag creation", .{});
```
Comment (Luukdegram) [inline cli/cmds.zig]: Showing tags does work, only the creation of them not yet. Now this function call always errors. You should only emit this panic when the user provided a name argument.

**Review by Luukdegram — CHANGES_REQUESTED** [review]

File: deps.zig (hunk 3 above)
Comment (ghost) [reply deps.zig]: Oop, forgot about it

File: cli/cmds.zig (hunk 4 above)
Comment (ghost) [reply cli/cmds.zig]: So, something like :

```zig
const name = if (args.len > 1) args[1] else null;
if(<condition name is not null>) {
  std.debug.panic();
}
```
?

Comment (Luukdegram) [reply cli/cmds.zig]: Yeah sounds good.

Comment (ghost) [reply cli/cmds.zig]: Fixed in https://github.com/Luukdegram/lemon/pull/1/commits/4ad27e7d4f4174bf904144861178c1039a6d60ec

File: deps.zig (hunk 3 above)
Comment (ghost) [reply deps.zig]: Fixed in https://github.com/Luukdegram/lemon/pull/1/commits/657e7ac95dfe5e4aaba4b55299906cf0a9036a50

**Comment by Luukdegram** [comment]
Thanks! :)
